#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     touch,          sensorNone)
#pragma config(Sensor, S3,     light,          sensorNone)
#pragma config(Sensor, S4,     sonar,          sensorNone)
#pragma config(Motor,  mtr_S1_C1_1,     leftWheel,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     arm,    tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void updateStatus();

task main() {
  while(true) {
    getJoystickSettings(joystick);

    motor[leftWheel] = joystick.joy1_y1;
    //add teleop code here

    if( joy1Btn(5) ) {
      motor[arm] = 50;
    }
    else {
      motor[arm] = 0;
    }

    if ( joy2Btn(10) ) {
      //write the battery status to the debug log
    }
    else if ( joy2Btn(11) ) {
      //reset the arm to a known position
    }

  }
}



void updateStatus() {
  writeDebugStreamLine("The status is now updated");
}
